### ISSUE TITLE
pmwa_pre bug for L>=10 in 1D

### ISSUE THREAD

**Issue by ryuikaneko** [issp-center-dev/dsqss#23]
Hi,

"pmwa_pre std.in" returns an error "error: D != number of L[]" when L>=10 and D=1.
It seems that the argument L=10 is passed as "1 [spacing] 0" rather than "10".
The script pmwa_pre works fine for D=2 and 3, though.

[log.txt](https://github.com/issp-center-dev/dsqss/files/5015001/log.txt)
[std.in.txt](https://github.com/issp-center-dev/dsqss/files/5015002/std.in.txt)

Ryui

**Comment by yomichi** [comment]
@ryuikaneko 
Thank you for reporting this.
I fixed in the PR #25. and will release v2.0.3 in a couple of days.

**Comment by ryuikaneko** [comment]
Thanks.
