### ISSUE TITLE
計算が終わらない

### ISSUE THREAD

**Issue by takeokato719** [issp-center-dev/dsqss#26]
dlaを用いて、２次元ハイゼンベルク模型(サイズ40x40, T=0.2)を128並列で回したら、計算が終わらなくなりました。
症状としては、一回終わらないパターンにはいると、計算が決して終わりません。

途中、ループが閉じないで永遠と系をさまよっているということはありますでしょうか？

**Comment by k-yoshimi** [comment]
@takeokato719 
ご報告ありがとうございます。
今の症状だけだと解析できませんので、以下の情報を提供していただけるでしょうか？

> 使用しているDSQSSのバージョン
> 実行に使用した入力ファイルとその出力

**Comment by Takuto36** [comment]
プログラムを回した者です。
DSQSSのバージョンは2.0.3です。
以下のファイルを実行しジョブを生成してスパコンに投げました。
（指定したパーティションのみ”パーティション名”に変えています。）
`import subprocess
import os
from dsqss.dla_pre import dla_pre
from dsqss.result import Results
from socket import gethostname

hostname = gethostname()
current_dir = os.getcwd()

seed1 = [12132400]
L1 = [38, 40]
N1 = [10]
T1 = [0.2]

M = 1
ntherm = 10000
ndecor = 1000
nmcs = 1000
ntau = 256

lattice = {"lattice": "hypercubic", "dim": 2}
hamiltonian = {"model": "spin", "M": M, "Jz": -1, "Jxy": -1}
parameter = {"ntherm": ntherm, "ndecor": ndecor, "nmcs": nmcs, "ntau": ntau}

g = open("./submit_all.sh",'w')
count = 0
for seed in seed1:
    s = seed % 20
    for L in L1:
        lfile = "lattice_L{}.xml".format(L)
        for N in N1:
            for T in T1:
                count = count + 1
                path_jobscript = "job{}.sh".format(count) 
                while os.path.exists(path_jobscript):
                    count = count + 1
                    path_jobscript = "job{}.sh".format(count)
                pfile = "param{}.in".format(count)
                ofile = "res_seed{}_M{}_L{}_T{}_nset{}_nthermal{}_ndecor{}_nmcs{}.dat".format(s, M, L, T, N, ntherm, ndecor, nmcs)
                lattice["L"] = L
                parameter["nset"] = N
                parameter["seed"] = seed
                parameter["beta"] = 1.0/T
                parameter["latfile"] = lfile
                parameter["outfile"] = ofile
                dla_pre(
                    {"parameter": parameter, 
                     "hamiltonian": hamiltonian, 
                     "lattice": lattice},
                    pfile,
            )
                dla_root = "$HOME/bin"
                f = open(path_jobscript,'w')
                script = """#!/bin/sh
#SBATCH -J "S{}L{}N{}T{}"
#SBATCH -p パーティション名
#SBATCH -N 1
#SBATCH -n 112
cd {}
date;srun -n 112 {}/dla {};date
""" .format(s, L, N, T, current_dir, dla_root, pfile)
                f.write(script)
                f.close()
                print("job{}.sh is generated.".format(count))
                g.write("sbatch job{}.sh\n".format(count))
g.close()
print("Wrote: submit_all.sh")
subprocess.call(['chmod','770','submit_all.sh']) `
L=38の場合は8分程度で添付したアウトプットファイルが出力されたのですが
L=40の場合は3日と16時間回しても計算が終わらなかった為、途中でジョブを切りました。
よろしくお願いいたします。
L=38の場合のアウトプットファイル
`C This is DSQSS ver.v2.0.3

I N_PROC = 112
P D       =            2
P L       =           38     38
P BETA    =       5.0000000000000000
P NSET    =           10
P NPRE    =         1000
P NTHERM  =        10000
P NDECOR  =         1000
P NMCS    =         1000
P SEED    =     12132400
P NSEGMAX =        10000
P NVERMAX =        10000
P BETA    = 5.000000000000
P NTAU    =          256
P NCYC    =            9
P ALGFILE = algorithm.xml
P LATFILE = lattice_L38.xml
P WVFILE = 
P DISPFILE  = 
P OUTFILE    = res_seed0_M1_L38_T0.2_nset10_nthermal10000_ndecor1000_nmcs1000.dat
P CFOUTFILE  = cf.dat
P SFOUTFILE  = sf.dat
P CKOUTFILE  = ck.dat
P SIMULATIONTIME   =     0.000000
R sign = 1.00000000e+00 0.00000000e+00
R anv = 2.22345864e+00 1.46452362e-04
R ene = -6.67093871e-01 9.56828928e-06
R spe = 3.18868866e-02 3.28988905e-03
R som = 1.59434433e-01 1.64494453e-02
R len = 8.74582269e+02 3.50557768e-01
R xmx = 4.37291135e+01 1.75278884e-02
R amzu = 2.14372279e-06 2.77030417e-06
R bmzu = 2.14372279e-06 2.77030417e-06
R smzu = 1.05726396e-02 1.47156414e-05
R xmzu = 5.28631980e-02 7.35782069e-05
R ds1 = 3.54699152e-07 5.32807975e-07
R wi2 = 1.47328741e+03 1.80460584e+00
R rhos = 5.10141071e-02 6.24863518e-05
R rhof = 1.42948799e+16 1.06871770e+16
R comp = 6.63897340e+35 5.81240988e+35
R time = 1.64986901e-05 1.08821966e-08
I [the maximum number of segments]          = 9079
I [the maximum number of vertices]          = 5262
I [the maximum number of reg. vertex info.] = 5`

**Comment by Takuto36** [comment]
プログラムを回した者です。
DSQSSのバージョンは2.0.3です。

添付したファイルを実行しジョブを生成してスパコンに投げました。
（指定したパーティションのみ”パーティション名”に変えています。）
L=38の場合は8分程度で添付したアウトプットファイルが出力されたのですが
L=40の場合は3日と16時間回しても計算が終わらなかった為、途中でジョブを切りました。
よろしくお願いいたします。

**Comment by Takuto36** [comment]
`import subprocess
import os
from dsqss.dla_pre import dla_pre
from dsqss.result import Results
from socket import gethostname

hostname = gethostname()
current_dir = os.getcwd()

seed1 = [12132400]
L1 = [38, 40]
N1 = [10]
T1 = [0.2]

M = 1
ntherm = 10000
ndecor = 1000
nmcs = 1000
ntau = 256

lattice = {"lattice": "hypercubic", "dim": 2}
hamiltonian = {"model": "spin", "M": M, "Jz": -1, "Jxy": -1}
parameter = {"ntherm": ntherm, "ndecor": ndecor, "nmcs": nmcs, "ntau": ntau}

g = open("./submit_all.sh",'w')
count = 0
for seed in seed1:
    s = seed % 20
    for L in L1:
        lfile = "lattice_L{}.xml".format(L)
        for N in N1:
            for T in T1:
                count = count + 1
                path_jobscript = "job{}.sh".format(count) 
                while os.path.exists(path_jobscript):
                    count = count + 1
                    path_jobscript = "job{}.sh".format(count)
                pfile = "param{}.in".format(count)
                ofile = "res_seed{}_M{}_L{}_T{}_nset{}_nthermal{}_ndecor{}_nmcs{}.dat".format(s, M, L, T, N, ntherm, ndecor, nmcs)
                lattice["L"] = L
                parameter["nset"] = N
                parameter["seed"] = seed
                parameter["beta"] = 1.0/T
                parameter["latfile"] = lfile
                parameter["outfile"] = ofile
                dla_pre(
                    {"parameter": parameter, 
                     "hamiltonian": hamiltonian, 
                     "lattice": lattice},
                    pfile,
            )
                dla_root = "$HOME/bin"
                f = open(path_jobscript,'w')
                script = """#!/bin/sh
#SBATCH -J "S{}L{}N{}T{}"
#SBATCH -p パーティション名
#SBATCH -N 1
#SBATCH -n 112
cd {}
date;srun -n 112 {}/dla {};date
""" .format(s, L, N, T, current_dir, dla_root, pfile)
                f.write(script)
                f.close()
                print("job{}.sh is generated.".format(count))
                g.write("sbatch job{}.sh\n".format(count))
g.close()
print("Wrote: submit_all.sh")
subprocess.call(['chmod','770','submit_all.sh'])    
`

**Comment by Takuto36** [comment]
プログラムを回した者です。
DSQSSのバージョンは2.0.3です。

添付したmake_jobscript.pyを実行しジョブを生成してスパコンに投げました。
（指定したパーティションのみ”パーティション名”に変えています。）
L=38の場合は8分程度で添付したアウトプットファイルが出力されたのですが
L=40の場合は3日と16時間回しても計算が終わらなかった為、途中でジョブを切りました。
よろしくお願いいたします。
インデントを含めたコードの貼り方が分からなかった為、以下のグーグルドライブにあげました。
よろしくお願いいたします。

https://drive.google.com/drive/folders/13NCWWvsxyJHwLBkvDfeYVmeWspw32RTB?usp=sharing

**Comment by Takuto36** [comment]
追加で1点補足です。
計算機による問題かを把握する為に
前回送らせていただいたプログラムをベースに
①クラスター計算機
②スーパーコンピューター
の2つで8並列にして計算プログラムを投げてみたところ
L=40では、①②のどちらでも計算はエラー無しで終了するのですが
（①は38秒、②は5分12秒で計算が終了。）
アウトプットファイルは出力されませんでした。
①②共にDSQSSのバージョンは2.0.3です。
お手数をおかけしますが、よろしくお願いいたします。

**Comment by takeokato719** [comment]
今ohtakaで確認したところ、L=40では以下のようなエラーメッセージがでてますね。
```
>>> The program is being run with MPI mode.( N_PROC = 8 ) 


+++++++++ input data +++++++++
RUNTYPE = 0

NSET    = 10
NTHERM  = 10000
NMCS    = 1000
SEED    = 12132400
NVERMAX = 10000
NSEGMAX = 10000

BETA    = 5
NTAU    = 256
ALGFILE = algorithm.xml
LATFILE = lattice_L40.xml
WVFILE = 
DISPFILE = 
OUTFILE = res_seed0_M1_L40_T0.2_nset10_nthermal10000_ndecor1000_nmcs1000.dat
CFOUTFILE  = cf.dat
SFOUTFILE  = sf.dat
CKOUTFILE  = ck.dat
SIMULATIONTIME   = 0
+++++++++ input data +++++++++
Determining hyperparameter NCYC : 9
Start main calculation.
Pool> ERROR. Attempt to extract from an empty pool.
Pool> ERROR. Attempt to extract from an empty pool.
Pool> ERROR. Attempt to extract from an empty pool.
Pool> ERROR. Attempt to extract from an empty pool.
Pool> ERROR. Attempt to extract from an empty pool.
Pool> ERROR. Attempt to extract from an empty pool.
.....
```

**Comment by yomichi** [comment]
対応遅れてすみません。
最後のログにあるエラーメッセージですが、 vertex などのオブジェクトとしてあらかじめ確保してあるものを使い切ってしまっているようです。
MPI 並列したときに計算が終わらないのは、これによっていくつかのプロセスが終了してしまっていて、最後にモンテカルロ平均のために merge するところですでに消えてしまった待ち人を待っているために思えます。

というわけで、
parameter の `nvermax` と `nsegmax` を増やしてみてください。

（ちょくちょく引っかかる人がいるので faq への追加というのも含めていい加減なにか考えます）

**Comment by k-yoshimi** [comment]
@takeokato719 @Takuto36 
これは上の回答で解決したのでしょうか？解決したようでしたら、closeをお願いします。

**Comment by takeokato719** [comment]
解決していますので、closeします。
