### ISSUE TITLE
使用メモリを減らす為に相対座標定義ファイルを変更すると、計算がうまく実行されない。

### ISSUE THREAD

**Issue by Takuto36** [issp-center-dev/dsqss#27]
サイズが大きな系で実空間表示の温度グリーン関数を出力しようとすると
計算時に使用するメモリ量が増えてしまう為、
自分の計算に必要なローカルなグリーン関数のみのアウトプットファイルを出力する為に
相対座標のデータを変更すると、以下の様なエラーが出てしまったのですが
何か解決方法はありますでしょうか。
よろしくお願いいたします。
以下に
L=2の2次元での変更前後の相対座標定義ファイルと
エラーの詳細を載せておきました。
よろしくお願いいたします。
DSQSSのバージョンは2.0.3です。

https://docs.google.com/document/d/1OYV-TY6j-qbvp4dYLBdizw8TL7T_Mot98Y0uGKtmJO4/edit?usp=sharing

**Comment by yomichi** [comment]
ご報告ありがとうございます。
すごくナイーブに、全サイトの組み合わせを前提としたコードになっていました。早めに直しておきます。

**Comment by yomichi** [comment]
@Takuto36 
直しました。 (develop ブランチ)
ご確認いただけると幸いです。

**Comment by Takuto36** [comment]
対応いただきありがとうございます。
確認してみます。

**Comment by Takuto36** [comment]
developブランチを使用し、相対座標ファイルを自分で変更したプログラムを動かした結果、対象のグリーン関数だけが出力されました。
対応いただきありがとうございました。
