### ISSUE TITLE
スタッガードな磁場をかけたハミルトニアンを作成する方法が分からない。

### ISSUE THREAD

**Issue by Takuto36** [issp-center-dev/dsqss#28]
シンプルモードでサイトの種類を指定できれば、xxz模型の磁場のパラメータhを配列で定義し、スタッガードな磁場をかけたハミルトニアンを扱うことができると考えているのですが、シンプルモードでサイトの種類を指定する方法が分かりませんでした。
対応よろしくお願いいたします。

**Comment by Takuto36** [comment]
スタンダードモードを使用し、latticeファイルで格子の種類を指定するように書き換え、hamiltonian.tomlファイルもスタッガードな磁場に合わせて書き換えることで、対応することが出来ました。

**Comment by Takuto36** [comment]
スタッガードな磁場をかける際に今までlattice.datのファイルで(0,0,0)(1,0,0)...などに対して自分でサイトtypeを2つに分けて指定し、ハミルトニアンでそれぞれのサイトtypeに対して逆向きの磁場を指定することで実現していたのですが、lattice.tomlファイルの場合どのように実現したら良いでしょうか。
よろしくお願いいたします。

**Comment by yomichi** [comment]
とりあえず現状の武器でなんとかする場合は、 2x2x2 の８site unit-cell として書いてしまうというのがあるかと思います。
L はユニットセルの繰り返し数であることには注意しておいてください。

**Comment by yomichi** [comment]
@Takuto36 
`is31` ブランチにて、 `std_latgen` による `lattice.dat` の生成部分を修正しました。

**Comment by Takuto36** [comment]
素早い対応いただき、ありがとうございます。
格子サイズが大きくてもdla_algがlattice.datファイルで使用できるようになったので、解決しました。
対応いただきありがとうございました。
