### ISSUE TITLE
実空間表示のSzSz温度グリーン関数の出力

### ISSUE THREAD

**Issue by Takuto36** [issp-center-dev/dsqss#37]
研究でDSQSSを用いる際、ローカル（実空間表示：i=j）SzSzの温度グリーン関数のアウトプットを用いたいと
考えているのですが
<S^{z}_{i}(τ)S^{z}_{j}(0)>
の様な温度グリーン関数を、出力出来るようにしていただくことは可能でしょうか。
突然のお願いで恐縮ですが、もし可能なようでしたら、よろしくお願いいたします。

**Comment by k-yoshimi** [comment]
@Takuto36 
ご連絡遅れすみません。簡単なコード変更で出力可能か確認してみます。

**Comment by Takuto36** [comment]
ソースファイルを書き換えることで、実装出来ました。
議論などしていただきありがとうございました。
