### ISSUE TITLE
Simulations of the XXZ model with finite field do not write the field `h` in the results file

### ISSUE THREAD

**Issue by abehersan** [issp-center-dev/dsqss#47]
Hi! The issue is as in the title.

It appears that whenever a simulation is run on the XXZ model with finite magnetic field, the magnitude of the field used is not written in the results file.
It is written in the parameters file however, as `h = something`.

My DSQSS version is `v.2.0.5`.

Thanks in advance for any comments!
Abraham

**Comment by yomichi** [comment]
As an input, the main program `dla` takes not Hamiltonian parameters like the magnetic field `h` but *algorithm* parameters like the scattering probability of the worm head. This makes `dla` deal with an arbitrary model. Therefore, `dla` doesn't know Hamiltonian and cannot write the value of `h` into the result file.
If necessary, please save Hamiltonian parameters to another file.

**Comment by abehersan** [comment]
I understand, thanks for the detailed answer! Closing now.
